version: '3.8'

services:
  rust-server:
    container_name: rust-server
    hostname: rust-server
    build: ./gameserver
    ports:
      - 10010:10010
      - 10010:10010/udp
      - 10011:10011
      - 10011:10011/udp
      - 10012:10012
      - 10012:10012/udp
      - 10013:10013
      - 10013:10013/udp
    volumes:
      - ./servers/crust/oxide:/server/oxide
      - ./servers/crust/server:/server/server
      - ./servers/crust/server_config.json:/server/server_config.json:ro
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"
    depends_on:
      - helper-server
  pg-uptrace:
    container_name: pg-uptrace
    hostname: pg-uptrace
    image: postgres:15
    volumes:
      - ./data/postgres-uptrace:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: $PG_UPTRACE_PASSWORD
      POSTGRES_USER: $PG_UPTRACE_USER
      POSTGRES_DB: $PG_UPTRACE_DB
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"      
  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: clickhouse/clickhouse-server
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"   
  uptrace:  
    container_name: uptrace
    hostname: uptrace
    image: uptrace/uptrace
    volumes:
      - ./config/uptrace.yml:/etc/uptrace/uptrace.yml:ro
    ports:
      - 14318:14318 #HTTP + webpanel
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"
    depends_on:
      - pg-uptrace
      - clickhouse
  pg-general:
    container_name: pg-general
    hostname: pg-general
    image: postgres:15
    volumes:
      - ./data/postgres-general:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: $PG_GENERAL_PASSWORD
      POSTGRES_USER: $PG_GENERAL_USER
      POSTGRES_DB: $PG_GENERAL_DB      
    ports:
      - 5437:5432      
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"   
  helper-server:
    container_name: helper-server
    hostname: helper-server
    build: ./helper-server
    environment:
      UPTRACE_DSN: 'http://IJALGDFSHGIKUHDS87HRIFE92318Y98RHBFN8EY3118092FDH3891H80F317HF80EN8NO8IFS@uptrace:14318?grpc=14317'
      ANALYTICS_SECRET: 'aboba'
      FEEDBACK_SECRET: 'aboba'
      DB_DSN: 'host=pg-general user=root password=HermanFuLLer dbname=default port=5432 sslmode=disable'
    logging:
        driver: "json-file"
        options:
          max-size: "5m"
          max-file: "5"   
    ports:
      - 8081:5555
    depends_on:
      - pg-general