FROM golang:alpine AS builder

ENV CGO_ENABLED 0

ENV GOOS linux

RUN apk update --no-cache && apk add --no-cache tzdata

WORKDIR /build

ADD go.mod .

ADD go.sum .

RUN go mod download

COPY . .

RUN go build -ldflags="-s -w" -o /app/exec ./main.go

FROM alpine


WORKDIR /app

COPY --from=builder /app/exec /app/exec

CMD ["./exec"]